### ISSUE TITLE
[1.7.10] [LINUX] Game crash when openning the waila config and close the config in game

### ISSUE THREAD

**Issue by quentin452** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#100]
### Describe the bug

Game crash when open the waila config and close the config in game

note : i use waila (fork) from gtnh https://github.com/GTNewHorizons/waila

### To Reproduce

1. Open a world
2. Open waila config
3. Close waila config
4. Crash the game

### Minecraft Version

Forge 1.7.10

### Logs/Screenshots/Videos

https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/files/10242945/crash-2022-12-16_06.35.33-client.txt

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
oh my god it's [1.7.10](https://howoldisminecraft1710.today/) again

**Comment by VidTu** [comment]
Support for all versions below 1.16.5 won't be provided anymore.
