### ISSUE TITLE
[Feature]Allows players to customize the button position of the MP interface

### ISSUE THREAD

**Issue by WzczChenX** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#102]
### Related problem

Considering the habitual conflict with the mod buttons, I hope to add this feature

### Describe the solution you'd like

Players can select this mod in the setting interface of the Mod menu and then make changes to the buttons in the configuration interface

**Comment by VidTu** [comment]
This feature is already in the mod. (You can configure X and Y position of any button and label)
