### ISSUE TITLE
[Bug] Can't login with Microsoft Account

### ISSUE THREAD

**Issue by littlekan233** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#103]
### Describe the bug

I want to add my Microsoft account in this mod. 
But when I accepted OAuth, It has an error: 
![image](https://user-images.githubusercontent.com/75866787/208617202-ec713ca1-dae1-434d-bdd3-55e52393f399.png)

### To Reproduce

1. Launch game
2. Open the main interface of this mod
3. Click “添加用户” (because my Minecraft's language is Chinese (Simplified). Maybe it is "Add an account")
4. Click “微软” (Maybe it is "Microsoft")
5. Login account in browser.
6. Back to game, and I will see the error.

### Minecraft Version

Fabric 1.19

### Checklist

- [x] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
1.19 is no longer supported, please use [1.19.3](https://modrinth.com/mod/in-game-account-switcher/version/8.0.1.1-fabric1.19) or [this unofficial fork](https://github.com/akemin-dayo/In-Game-Account-Switcher/releases/tag/8.0.1-akemi).

**Comment by littlekan233** [comment]
> 1.19 is no longer supported, please use [1.19.3](https://modrinth.com/mod/in-game-account-switcher/version/8.0.1.1-fabric1.19) or [this unofficial fork](https://github.com/akemin-dayo/In-Game-Account-Switcher/releases/tag/8.0.1-akemi).

oh i know
thx
