### ISSUE TITLE
[Bug] Error while adding certain account

### ISSUE THREAD

**Issue by JupiterBlooper** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#106]
### Describe the bug

When I try to add one specific account i get the error:   java.lang.IllegalArgumentException: authXSTS response: 401
It only happens when i try to add a specific account, which is 100% playable otherwise. Adding it offline works, but online doesnt

### To Reproduce

1. Launch the game
2. Try to add account url1 to account switcher
3. Sign into Microsoft successfully
4. Get error

### Minecraft Version

1.19.3

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by Khoeckman** [comment]
Still getting this exact error message for forge-1.8.9:
`java.lang.IllegalArgumentException: authXSTS response: 401`
