### ISSUE TITLE
I hope to support whether to automatically refresh the first online account when logging in to the first online account after the game is started

### ISSUE THREAD

**Issue by lizheyo77** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#110]
### Related problem

I hope to support whether to automatically refresh the first online account when logging in to the first online account after the game is started

### Describe the solution you'd like

I hope to support whether to automatically refresh the first online account when logging in to the first online account after the game is started

**Comment by VidTu** [comment]
This mod automatically refreshes accounts on login.
If you're asking for "auto-login", then this mod is not intended to do so.
(Just add your account into launcher)
