### ISSUE TITLE
Does not work for 1.19.0, fabric.

### ISSUE THREAD

**Issue by IzRainy** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#112]
### Describe the bug

when I try to add an account it does not allow me to.
<img width="1440" alt="Screenshot 2023-03-22 at 15 00 15" src="https://user-images.githubusercontent.com/127672220/226928318-564bf16a-0e9c-41c2-837e-332a8abc5e62.png">

Logs: Unknown error: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to
requested target

### To Reproduce

1. open the game
2. go to account switcher, choose 'add account'
3. tap 'microsoft auth' and connect to another account
4. after you're done logging in on your alt, you're set and will receive this msg 
'Unknown error: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to
requested target'

### Minecraft Version

Fabric 1.19 (1.19.0) + API + Mod menu

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
this version is not latest. you can use [this unofficial fork](https://github.com/akemin-dayo/In-Game-Account-Switcher/releases/tag/8.0.1-akemi).
