### ISSUE TITLE
[Bug] {"You are currently logged in as xxx" is not displayed.}

### ISSUE THREAD

**Issue by Luke2206** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#114]
### Describe the bug

I upgraded my game today from Fabric 1.19.3 to Fabric 1.19.4 and noticed that the message "You are currently logged in as xxx" is not displayed. 
how can I change this?

### To Reproduce

1. Launch the Game

### Minecraft Version

Fabric 1.19.4

### Logs/Screenshots/Videos

https://postimg.cc/gallery/W3XKLsQ 

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
Unable to reproduce.
