### ISSUE TITLE
[Bug] {getProfile: 404}

### ISSUE THREAD

**Issue by triesharder** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#115]
### Describe the bug

When trying to add a Microsoft Account:

Using version v8.0.1.2 on
![image](https://user-images.githubusercontent.com/89689590/232083737-4998c91a-ffca-462d-84bd-110ed6fb7470.png)

![image](https://user-images.githubusercontent.com/89689590/232083530-d049bd50-46b3-4cf8-b8f3-6523f676bc30.png)

Is this related to #106 and #113 ?

### To Reproduce

1. Launch the game.
2. Try to add a Microsoft Account normally.
3. getProfile 404.

### Minecraft Version

Fabric 1.19.4

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by JTricky** [comment]
Same issue with Windows 11. Game version 1.19.2 Forge 43.2.21

**Comment by Bxrked** [comment]
im having the same problem but we can log in manually from original minecraft launcher and launch the game with the bugged account but if i trying to log in with in game account switcher i simply can't

**Comment by xFreakss** [comment]
@JTricky I own a copy of the game since 2015, never played minecraft without java

**Comment by xFreakss** [comment]
Everything works very well with latest, the version that i'm using its 8.0.2 for 1.20.1
