### ISSUE TITLE
[Bug] {InGame account switcher Multiplayer is disabled}

### ISSUE THREAD

**Issue by BanAvade** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#116]
### Describe the bug

This error when i change mc account with ingame switcher to no license account

### To Reproduce

1.Launch the game
2.Change account
3.see multiplayer is disabled
4.raging

### Minecraft Version

Forge 1.16.5

### Logs/Screenshots/Videos

https://imgur.com/4Ub03y2

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by BanAvade** [comment]
> apparently this is an issue for all 1.16.5 offline accounts, even for vanilla ones. (e.g. using Prism Launcher offline accounts) not sure how to fix this as force-enabling multiplayer button even when it's disabled may lead to issues with Mojang's EULA and Modrinth/CurseForge moderation teams

yesterday released new version of 1 16 5 minecraft which fix all offline accounts, prism launcher also not work

**Comment by VidTu** [comment]
1.16.5 is no longer supported.
