### ISSUE TITLE
[Bug] {No skins are displayed in the account overview or ingame.}

### ISSUE THREAD

**Issue by Luke2206** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#118]
### Describe the bug

More and more often I have the error that no player's skin is displayed ingame. Likewise, no skins are often displayed in the account overview.

### To Reproduce

1. start the game with the latest version IAS
2. Open the IAS Gui
3. check if there are skins
4. if there are only the defaultMc skins, there are also no skins ingame.

### Minecraft Version

Fabric 1.20.1

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
Unable to reproduce and if the skins are not being displayed in-game, that's a problem on your side. (Maybe you're getting rate-limited by Mojang or your ISP blocks Mojang's servers)
