### ISSUE TITLE
[Bug] The following error occurred when I added my account

### ISSUE THREAD

**Issue by AnZhuoMan** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#119]
### Describe the bug

Unable to add account

### To Reproduce

I signed in using Microsoft and agree to the terms, but the following is prompted

### Minecraft Version

1.8.9

### Logs/Screenshots/Videos

https://postimg.cc/QHW6J7yf

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
1.8.9 is no longer supported.
