### ISSUE TITLE
[Bug] Virus?

### ISSUE THREAD

**Issue by SinanAkkoyun** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#121]
### Describe the bug

Is it normal that I see this after logging in with microsoft?

![image](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/assets/43215895/1f410912-d931-4e6e-820f-a2fb2427b31f)

Its hosted on localhost:59125

### To Reproduce

log in with a MS account

### Minecraft Version

1.20.1, all latest

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by SinanAkkoyun** [comment]
lmao

**Comment by The-Fireplace** [comment]
Where did you download the mod from?

**Comment by VidTu** [comment]
Yes it is normal. 🐷 
([Reference](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/blob/main/shared/src/main/resources/authPage.html))

**Comment by SinanAkkoyun** [comment]
Okay thanks hahaha
