### ISSUE TITLE
Account doesn't work (in MC Versions above 1.12)

### ISSUE THREAD

**Issue by cooldroider** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#122]
### Describe the bug

I needed to enter the special account that has unique cape. I put account name, and tried to login both ways (regular and offline). When I entered the game, there still was my own account. In 1.12.2 everything works fine. What to do?

### To Reproduce

1. Enter In-Game Account Switcher menu
2. Add any user
3. Login regular way or offline
4. Enter The game
Boom, and you still have your acc!

### Minecraft Version

Any Fabric version

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
What do you mean by "same account"? If your name/UUID didn't change, then please share your mod list. If the inventory in the singleplayer didn't change, that's vanilla behavior and probably won't be changed

**Comment by VidTu** [comment]
No response.
