### ISSUE TITLE
Hello, I'm asking you to make fabric or quilt for version 1.20.2 on morinth, thank you very much!

### ISSUE THREAD

**Issue by verixyt3** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#126]
### Related problem

Hello, I'm asking you to make fabric or quilt for version 1.20.2 on morinth, thank you very much!

### Describe the solution you'd like

Hello, I'm asking you to make fabric or quilt for version 1.20.2 on morinth, thank you very much!

### Additional context

Hello, I'm asking you to make fabric or quilt for version 1.20.2 on morinth, thank you very much!

**Comment by VidTu** [comment]
Done.
