### ISSUE TITLE
[Feature] {Add password manager for offline accounts}

### ISSUE THREAD

**Issue by dj0j** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#127]
### Related problem

Add password manager for offline accounts. 

### Describe the solution you'd like

Add that for every account and server

**Comment by VidTu** [comment]
what do you mean "password manager" for offline accounts. offline accounts don't require passwords.

**Comment by The-Fireplace** [comment]
Servers running in offline mode typically have a plugin that allows users to use commands to assign and use a password to log in, to prevent people from using others' names to gain access to their stuff.

**Comment by VidTu** [comment]
i don't think this a feature that should be in this mod. it's a great idea for a separate mod (might as well do it), but it's implementation and ui will be different probably

**Comment by VidTu** [comment]
won't be added into this mod
