### ISSUE TITLE
When I Create My Skins It Changes To Steve, Alex And Many more default variants

### ISSUE THREAD

**Issue by ProbennyKing1971** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#129]
### Describe the bug

The Second i open my fake account and log it in to my LAN World. It Changes to Steve and Alex Or Many other variants.

### To Reproduce

For example: I create a Fake account and name it ShadowStalker. I Put in my Main. Open To LAN, Put My alt in, and I see my alt has changed to steve or alex Or Many more default variants, But in my Fake Account view. My Skin Is Exactly The Skin i'm Wearing.

Can someone help me with this

### Minecraft Version

Fabric 1.20.1

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by ProbennyKing1971** [comment]
i meant "But in my Fake Account view. My MAIN ACCOUNT Skin Is Exactly The Skin i'm Wearing."

**Comment by VidTu** [comment]
vanilla bug, won't fix.
https://bugs.mojang.com/browse/MC-135339
