### ISSUE TITLE
Add an option to edit UUID

### ISSUE THREAD

**Issue by C0rn3j** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#13]
Minecraft skin lookup by Nickname is deprecated, and it may be replaced with UUID only in the future.

Adding the support to edit UUID before that happens would be awesome!

**Comment by The-Fireplace** [comment]
Since when? Do you have any documentation?

**Comment by C0rn3j** [comment]
https://crafatar.com/#meta-usernames

"Looking up players by username has officially been deprecated by Mojang ever since UUIDs were introduced."

Can't find the source coming from Mojang but you will probably know where to look better than I do.

**Comment by The-Fireplace** [comment]
Yeah, looking up players. Their skins are still stored by player name though, not uuid.
