### ISSUE TITLE
[Feature] 1.20.3/4 Support

### ISSUE THREAD

**Issue by R00tB33rMan** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#131]
### Related problem

Yes, it's me again!

In-Game-Account-Switcher loads and the main menu works, up until you actually open the account switcher menu.

### Describe the solution you'd like

Make the account switcher menu work with 1.20.3/4.

### Additional context

I'm not entirely sure if you're aware if this release is out yet; however, it seems last time around this post helped notify you! I really appreciate your contributions towards keeping this resource maintained and working.

**Comment by VidTu** [comment]
will do after i get better (and won't forget, ping me if there's nothing in 1-2 weeks)

**Comment by R00tB33rMan** [comment]
> will do after i get better (and won't forget, ping me if there's nothing in 1-2 weeks)

No worries! Make sure to take care of yourself! Just wanted to make sure all was well and if there was any consideration for a 1.20.3/4 branch. Thank you for your hard work!

**Comment by VidTu** [comment]
ok i was in a progress of [rewriting most of the code from the ground up](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/tree/rewrite), but i realized this will take some time, so i updated 8.x.x version for 1.20.4 and it's now available on modrinth and curseforge. (not yet available on curseforge at the time of writing, but will be a few minutes, they're using their "advanced antivirus")

**Comment by R00tB33rMan** [comment]
No worries. Appreciate it a ton! Really excited for that other change then too, however!
