### ISSUE TITLE
[Feature] {short feature description here}

### ISSUE THREAD

**Issue by Nighvisit** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#132]
### Related problem

There should be any way to add skin in offline mod.
Tlauncher account don't work in 1.20.1

### Describe the solution you'd like

Add any way to use skin in offline mode. 

### Additional context

 I can't add skin in offline mode. If I could ?

**Comment by VidTu** [comment]
offline accounts load skins from online accounts with the same name

**Comment by VidTu** [comment]
tlauncher and other cracked launchers are not supported
