### ISSUE TITLE
[Bug] cannot login with microsoft account in 1.7.10

### ISSUE THREAD

**Issue by KillerGolem69420** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#133]
### Describe the bug

I'm use it to play in 1.7.10. However, I cannot use microsoft account to login

### To Reproduce

1. Click add account
2. Click microsoft(Beta)
3. Click "Want to let this application access your information?" accept button on google
4. It tell me cannot use microsoft

### Minecraft Version

Forge 1.7.10

### Logs/Screenshots/Videos

https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/assets/113170877/c1024026-5ca8-4ab1-86f6-15050ab76144

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
1.7.10 is not supported and is [older than some minecraft players](https://howoldisminecraft1710.today/). update your game.
