### ISSUE TITLE
[Microsoft login] {Error popping up!}

### ISSUE THREAD

**Issue by MonkeeeCs** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#136]
### Describe the bug

So when i normally want to login with microsoft it shows an error and idk what to do!
- Account is not a child (under 18)
- Account has xbox account
- Account has premium Minecraft bought!
- Xbox app is installed
(No crashes)
I am using  a **Curseforge desktop app** if you need or want to know!

### To Reproduce

1. Lunch the game
2. open the account menager
3. add account
4. Choose "Microsoft (beta)" as a login method
5. Accept the "conditions" on browser and wait!
6. Boom, the error is here

### Minecraft Version

Forge 1.16.5 (using forge desktop app to launch and play with mods)

### Logs/Screenshots/Videos

[Image Link](https://imgur.com/a/Q4kWk4E)

### Checklist

- [x] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by MonkeeeCs** [comment]
This may only be a bug for me but not sure yet (i mean device)

**Comment by VidTu** [comment]
1.16.5 is no longer supported.
