### ISSUE TITLE
[Bug] {short bug description here}

### ISSUE THREAD

**Issue by buzepvp** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#137]
### Describe the bug

I am using ingameaccountswitcher in lunar client, and in mod menu he see it, but when im turnin on multiplayer button, i dont have the button on the multiplayer

### To Reproduce

start lunar
open mod menu
click on the mp button
and dont work

### Minecraft Version

fabric 1.16.5

### Logs/Screenshots/Videos

https://youtu.be/7jP7EMGrkFo

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
1.16.5 is no longer supported.
