### ISSUE TITLE
Cant log back into original account used to start game

### ISSUE THREAD

**Issue by jclgc** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#14]
Whenever I launch my game I'm logged in to one account, then I can switch to others, but I can't log back in to the original account. Adding it says "invalid username/password"

**Comment by jclgc** [comment]
Mod version 7.0.1 for MC 1.8.9

**Comment by NPCtom** [comment]
Not a mod issue. Client side. Please reset your password at mojang.com
