### ISSUE TITLE
Hardware encryption issue

### ISSUE THREAD

**Issue by melonkowymelonek** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#148]
Accounts added on version 1.20.6 don't work on 1.20.1 and vice versa.

Quilt Loader 1.20.1, 1.20.6
IAS 9.0.0-beta.4

**Comment by VidTu** [comment]
that's pretty odd. what launcher are you using?

**Comment by VidTu** [comment]
that's pretty odd. what launcher are you using? @melonkowymelonek

**Comment by VidTu** [comment]
also, do you, by any chance, use more than one graphics adapter/card? (e.g. both processor[internal] and external or something else)

**Comment by VidTu** [comment]
ok, this is most likely caused by OSHI changes between versions.

**Comment by VidTu** [comment]
should be fixed in 9982fe870560482645835b4dd4193760a1f9b985, will be released sometime in the future

**Comment by VidTu** [comment]
Fixed in 9.0.0-beta.5.
