### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by nitto798** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#151]
pls help i cant edit xD
![obraz_2024-05-21_224230002](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/assets/81933703/f5a7d1cd-2ec8-4519-893c-7fd0fcb78f40)
![image](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/assets/81933703/68bbfba1-36e1-4cae-b185-73d2217fd306)

**Comment by VidTu** [comment]
just select and click "edit"?..

**Comment by nitto798** [comment]
> just select and click "edit"?..

![Uploading image.png…]()
i cant edit

**Comment by VidTu** [comment]
you haven't attached the image properly

**Comment by VidTu** [comment]
no response.
