### ISSUE TITLE
show skins in offline accounts

### ISSUE THREAD

**Issue by WhyNevermore** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#153]
![image](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/assets/171009706/10ef4ef2-6b77-4bdd-a77f-00fa9daaba30)
🐷🐷

**Comment by VidTu** [comment]
added in 4b060384709b13d9945dfdb0043158e2aba08781.
dev builds will be available here: https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/actions
will be released onto modrinth, curseforge, etc. in the future
(readd offline accounts for this to take effect)

**Comment by VidTu** [comment]
added in 9.0.0.
