### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by WhyNevermore** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#155]
when ias on 1.21?

**Comment by VidTu** [comment]
already as [snapshot builds](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/actions).
will be released to modrinth, curseforge, etc. in the future
<details>
<summary>please don't nag mod developers right away</summary>
<img src="https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/assets/60929459/7d7556b7-4ad4-49f8-a330-85fa4098b83d">
</details>

**Comment by VidTu** [comment]
semi-blocked by architectury loom upstream, can release without forge version ofc.
if upstream's 1.20.6/1.21 forge support PR is not going to be merged within a week, i'm going to release without forge 1.20.6/1.21.

**Comment by VidTu** [comment]
added in 9.0.0.
