### ISSUE TITLE
End page not working

### ISSUE THREAD

**Issue by xMelonekMaX** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#156]
![image](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/assets/96833801/36df51d2-58c9-4b96-891a-d899b22b0580)
[latest.log](https://github.com/user-attachments/files/15835507/latest.log)

Minecraft 1.20.6
Fabric Loader 0.15.11
Fabric API 0.100.0
IAS 9.0.0-beta.5

**Comment by VidTu** [comment]
fixed in snapshot builds. (already)

**Comment by xMelonekMaX** [comment]
ok, works
