### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by PythonNerd12** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#158]
Ello i signed into a account using ur mod and i reluanched minecraft, and the account is gone idk why.

**Comment by VidTu** [comment]
cool, but you probably want to share things like:
- your modloader
- its version
- mc version
- mod version
- your logs

**Comment by VidTu** [comment]
no response.

**Comment by PythonNerd12** [comment]
ok
