### ISSUE TITLE
Hope the author can update a player account data saved in the config folder for the 1.21 version

### ISSUE THREAD

**Issue by routhing** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#166]
Because most integration packages put files into the “Root” directory of the “GameDir”, the files are confused, so I hope the author can update a player account data saved in the config folder for the 1.21 version, I can't thank you enough.🤓

**Comment by VidTu** [comment]
what

**Comment by VidTu** [comment]
no response.
