### ISSUE TITLE
The zh_CN translation file of this game

### ISSUE THREAD

**Issue by layou233** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#17]
I translated this mod to Chinese(Simplified) when I had nothing to do at home. XD
I'm Chinese so I can make sure that it is accurate.
The file name is "zh_CN.lang" and it should using UTF-8.
If you want zh_TW, you can use Google and translate this to Chinese(Traditional). :-)
There is only one difference between Chinese(Simplified) and Chinese(Traditional) is that they just look different.

ias.loggedinas=你正在此账号中游玩: 
ias.selectaccount=选择一个账号
ias.offlinemode=你正在以离线模式游玩!只能进入无正版验证的服务器.
ias.addaccount=添加账号
ias.login=登录
ias.offline=(离线模式)
ias.delete=删除
ias.alt=账户
ias.username=游戏名或正版邮箱:
ias.password=密码(正版玩家请输入):
ias.edit=编辑
ias.editaccount=编辑账号
ias.search=搜索
ias.cfg.casesensitive=区分大小写的搜索
ias.cfg.casesensitive.tooltip=需要区分大小写进行账号搜索吗?
ias.cfg.enablerelog=重新登录
ias.cfg.enablerelog.tooltip=启用重新登录到您帐户的功能.
ias.updatejava=更新Java
ias.premium=可用
ias.notpremium=暂不可用
ias.timesused=使用次数:
ias.lastused=最后使用:
ias.alreadyloggedin=你已经登录到这个账号了.
ias.reloadskins=重载皮肤

**Comment by layou233** [comment]
Tips: "cancel"="取消"
I cannot find anything corresponding likes "ias.cancel" in en_US.lang so I didn't translated it in this file. :-(

**Comment by The-Fireplace** [comment]
Would you be willing to fork the repository, add the file, and make a pull
request?

**Comment by The-Fireplace** [comment]
There, a new build has been published to CurseForge. Enjoy!
