### ISSUE TITLE
Latest Mod version not compatible with Fabric 1.21.1

### ISSUE THREAD

**Issue by SkyWolfXP** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#171]
![{EDA8BBAA-4C54-49E8-8F2E-2B5B1B73B397}](https://github.com/user-attachments/assets/9fcf9524-0433-4069-8827-00182202d13c)

Although 1.21.1 is available in the repo... Could we please have a build that supports 1.21.1?

**Comment by BlueFox0010** [comment]
[https://www.mediafire.com/file/9ezzdsjruy8ogpl/IAS-Fabric-1.21.1-9.0.2-SNAPSHOT.jar/file](url)
use this

**Comment by VidTu** [comment]
Alpha builds for 1.21.1 and 1.21.3 have been uploaded to Modrinth. They aren't (and won't be) available on CurseForge and GitHub due to the fact I don't want to manually upload 35 files. See #185 for details.
