### ISSUE TITLE
Unable to connect to Microsoft authentication servers

### ISSUE THREAD

**Issue by yusoxd** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#178]
![image](https://github.com/user-attachments/assets/944543ce-a1ce-41a6-bf17-97e4801e58cf)
now what

**Comment by VidTu** [comment]
definitely not caused by IAS, check your internet, firewall, hosts file, launcher, proxy, other mods.

**Comment by yusoxd** [comment]
> definitely not caused by IAS, check your internet, firewall, hosts file, launcher, proxy, other mods.

yeah the issue was my router's firewall blocking connection to servers
thank you
