### ISSUE TITLE
i dont have an option to make go offline account

### ISSUE THREAD

**Issue by Skibidi213123** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#184]
i can only make account with microsoft or login and password
i dont have an option to make account without password like go offline option is not avaible for me
![Снимок экрана 2024-11-13 180052](https://github.com/user-attachments/assets/d8573021-bff7-43dc-9fb5-01bea01d8a5d)
![Uploading Снимок экрана 2024-11-13 180047.png…]()

**Comment by VidTu** [comment]
1. У тебя 1.16.5 и она в целом уже не поддерживается.
2. Второй скриншот не до конца загрузился, перезалей.

**Comment by VidTu** [comment]
нет ответа. (no response)
