### ISSUE TITLE
pls fix it

### ISSUE THREAD

**Issue by madarchod-69** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#190]
in game acconut switcher not working in 1.8.9

**Comment by VidTu** [comment]
tested it and **it works** just fine. note that 1.8.9 is old and unsupported. sometimes you need to update your Java build, from Java 8 build 51/131/151/161 (or any other older build) to the latest Java 8 build. you can download newer Java 8 from (at your choice): [Temurin](https://adoptium.net/temurin/releases/?os=any&version=8&package=jdk) (by Eclipse), [Zulu](https://www.azul.com/downloads/?version=java-8-lts&package=jdk#zulu) (by Azul), [Corretto](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html) (by Amazon), or any other vendor at your choice. you can search for "download java 8".
