### ISSUE TITLE
Microsoft Account Support

### ISSUE THREAD

**Issue by Wven** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#27]
I am unable to sign in with my microsoft account through the in game account switcher. It will not display an error after i have typed my email and passcode, but rather it will just not budge and not work even after repeated clicks. MC 1.16.5, Mod 7.07, Fabric, Unknown, and Unknown.

**Comment by VidTuGit** [comment]
Microsoft account support was added in 7.1.0-pre1. It doesn't exist in 7.0.7.
If you have any issues with 7.1.0-pre1, describe them.
