### ISSUE TITLE
Starting The mod on 1.17 crashes the game : An Unexpected issue occurred And the game has crashed

### ISSUE THREAD

**Issue by Rainb0-0** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#28]
**Describe the bug**
when running the Game with the mod Crashes without crash log
tried removing and worked

**To Reproduce**
1. Install fabric mod loader 0.11.3 on 1.17
2.add In-Game Account switcher version 7.1.0-pre2
3.Launch the game
4.Crashes

**Logs/Screenshots/Videos**
[Crash ScreeShot](https://ibb.co/JtKDSdd)

**Versions**
 - Minecraft: 1.17
 - Mod Version: 7.1.0-pre2
 - Loader type: fabric
 - Loader version 0.11.3
 - Fabric API: 0.34.9-1.17

**Comment by VidTuGit** [comment]
Oh. 7.1.0-pre2 was made for 1.17 pre-release. I'll fix that.
###### For future issues: this screenshot does not help with fixing. You will need to check your ".minecraft/crash-reports" folder and upload the crash report (not for this time though).

**Comment by VidTuGit** [comment]
The [fixed](https://www.curseforge.com/minecraft/mc-mods/in-game-account-switcher/files/3345483) version released.
