### ISSUE TITLE
Microsoft (Beta) Account not linked

### ISSUE THREAD

**Issue by Jacrispys** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#29]
**Describe the bug**
When I try to log into a microsoft linked account the web browser opens and asks to verify but when I log in the client gives me the error that the account doesn't have a minecraft account linked. Which it does.

**Logs/Screenshots/Videos**
![image](https://user-images.githubusercontent.com/69219325/122514564-fc63c700-cfc0-11eb-9b93-f26a180b8aac.png)

https://pastebin.com/8Lsb1GrQ

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.8.9
 - Mod Version: 7.1-pre2
 - Loader type: forge
 - Loader version IDK (too lazy)

**Comment by VidTuGit** [comment]
I'm unable [to reproduce](https://www.youtube.com/watch?v=B7IfKPBAp3I) this issue.
I have some questions:
1. Are you sure you're logged in to a valid account in the browser?
2. Are you using an official launcher?

**Comment by VidTuGit** [comment]
According to [wiki.vg](https://wiki.vg/Microsoft_Authentication_Scheme#Authenticate_with_XSTS), this error should only occur when:
- The account is a child (under 18) and cannot proceed unless the account is added to a Family by an adult. This only seems to occur when using a custom Microsoft Azure application. When using the Minecraft launchers client id, this doesn't trigger.
- The account doesn't have an Xbox account. Once they sign up for one (or login through minecraft.net to create one) then they can proceed with the login. This shouldn't happen with accounts that have purchased Minecraft with a Microsoft account, as they would've already gone through that Xbox signup process.
So there should be a 0% chance to have this error when logging in to a valid account.

**Comment by Jacrispys** [comment]
> According to [wiki.vg](https://wiki.vg/Microsoft_Authentication_Scheme#Authenticate_with_XSTS), this error should only occur when:
> 
> * The account is a child (under 18) and cannot proceed unless the account is added to a Family by an adult. This only seems to occur when using a custom Microsoft Azure application. When using the Minecraft launchers client id, this doesn't trigger.
> * The account doesn't have an Xbox account. Once they sign up for one (or login through minecraft.net to create one) then they can proceed with the login. This shouldn't happen with accounts that have purchased Minecraft with a Microsoft account, as they would've already gone through that Xbox signup process.
> 
> So there should be a 0% chance to have this error when logging in to a valid account.

account was aged at 17 instead of 18 fixed thanks!
