### ISSUE TITLE
Editing Account Details crash.

### ISSUE THREAD

**Issue by Jacrispys** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#30]
**Describe the bug**
After editing my account details and clicking log in my game crashed...

**Logs/Screenshots/Videos**
https://pastebin.com/uvG89GpD

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.8.9
 - Mod Version: 7.1pre2
 - Loader type: forge

**Comment by Jacrispys** [comment]
After some more testing this crash happens when you click login after updating any info on the page without leaving the gui and returning

**Comment by VidTuGit** [comment]
This issue impact all versions. Will fix and release a new version.
