### ISSUE TITLE
Username shows invalid

### ISSUE THREAD

**Issue by Jacrispys** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#31]
**Describe the bug**
When logging into a mojang migrated to minecraft.net account I cannot login with my username, inputting username and password returns invalid credentials, but if I set username to my email it will correct the GUI with my username and will log me in, but editing account details still shows email

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.8.9
 - Mod Version: 7.1pre2
 - Loader type: forge

**Comment by VidTuGit** [comment]
I guess, something like this: ![](https://i.imgur.com/VrnwSvG.png) is okay.

Or I should hide it behind the "hint" icon?

**Comment by The-Fireplace** [comment]
Why don't we Call the "Login" field "Email"? I don't think there are many users out there still using old mojang accounts

**Comment by VidTuGit** [comment]
Yep, that's good too.

**Comment by 2xsaiko** [comment]
> I don't think there are many users out there still using old pre-mojang accounts

I don't think there's any, actually. Pretty sure Mojang disabled all non-migrated accounts quite some time ago.

**Comment by The-Fireplace** [comment]
In that case I'd suggest changing it and just leaving the other localizations alone until someone updates them.

**Comment by VidTuGit** [comment]
Fixed in 7.1.0-pre3.
