### ISSUE TITLE
Account not working

### ISSUE THREAD

**Issue by awaWaterrrr** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#32]
when i load up my game, switch to my alt and try to switch back, it says my main account isn't premium and also the account details are wrong

if i load on my alt and try to switch to my main it says the same

i've deleted and readded the mod, logged out of both accounts on my mc launcher

**Comment by Phinwing** [comment]
same bug

**Comment by VidTuGit** [comment]
Did you put your nickname or email in the "username" field?
