### ISSUE TITLE
The mod thinks my account is cracked.

### ISSUE THREAD

**Issue by Phinwing** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#33]
**Describe the bug**
My account, even though I literally changed my password, thinks my account is cracked. Yes I reloaded my minecraft.

**To Reproduce**
This would require me to tell you my account/password.

**Logs/Screenshots/Videos**
![image](https://user-images.githubusercontent.com/52756813/123693525-067d9500-d80d-11eb-9da8-143906f233aa.png)
![image](https://user-images.githubusercontent.com/52756813/123693559-0e3d3980-d80d-11eb-928a-b0b0a7aebda0.png)
Password is 100% my password, unless copy/paste is broken.

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.17
 - Mod Version: 7.1.0
 - Loader type: Fabric
 - Loader version: 0.11.6
 - (Fabric only) Fabric API: 0.36.0

**Comment by 2xsaiko** [comment]
I assume you need to put your email address in, not your username.

**Comment by VidTuGit** [comment]
Yeah, you should use email.


I wanted to delay the mod update until Forge 1.17 is released, but looking at [their progress](https://dpeter99.github.io/ACFT/notes/forge_117.html), I'm starting to update now.

**Comment by VidTuGit** [comment]
Use email as username.
The field will be renamed in the next update.
