### ISSUE TITLE
After logging in, you should be returned to the title screen, Also prompt for confirmation before deleting an account

### ISSUE THREAD

**Issue by GodBleak** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#34]
I keep deleting accounts when I mean to return to the main menu. I don't know why, but my subconscious expects a "done" button where the delete button is. But rather than putting in a "done" button, I think it makes more sense to confirm before you delete an account and return to the title screen after you log in. 

Thanks for your work!

**Comment by VidTuGit** [comment]
Okay, I'll add a confirmation screen.

**Comment by VidTuGit** [comment]
Should be fixed in 7.1.0.
