### ISSUE TITLE
Skin rendering issue

### ISSUE THREAD

**Issue by hashalite** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#35]
**Describe the bug**
Some skins are rendered incorrectly in the skin preview.

**To Reproduce**
Add an account with [this skin](https://user-images.githubusercontent.com/71229440/127810952-27e0162b-b262-4d77-a733-2a6b7d80ebe4.png).

**Logs/Screenshots/Videos**
![skin](https://user-images.githubusercontent.com/71229440/127812246-47910b92-3359-49ce-97fa-1c6128a92f04.png)

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.17.1
 - Mod Version: 7.1.0-pre3
 - Loader type: Fabric
 - Loader version 0.11.6
 - Fabric API: 0.37.1

**Comment by VidTuGit** [comment]
Can you tell a nickname of the account with this skin?

**Comment by hashalite** [comment]
The account [xlt](https://namemc.com/profile/xlt.7) has it

**Comment by VidTuGit** [comment]
Should be fixed in 7.1.0.
