### ISSUE TITLE
[Feature Request] More Customizable buttons settings

### ISSUE THREAD

**Issue by Soham52** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#39]
**Is your feature request related to a problem? Please describe.**
the main menu does not look much pleasing

**Describe the solution you'd like**
an option to disable the button and tooltip displayed on the main menu and only show those in the multiplayer tab

**Additional context**
it can be in the config file or in the in game menu

**Comment by VidTuGit** [comment]
Added in 7.1.3.
