### ISSUE TITLE
Not being able to add more than one microsoft account

### ISSUE THREAD

**Issue by 808Ender** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#41]
**Describe the bug**
Cannot add more than one microsoft account. Wether it be a freshly migrated or a microsoft account that was bought after they moved from mojang accounts. Any microsoft account can be added but you cannot add more than one

**To Reproduce**
1. Add one microsoft account
2. After completing adding the first one add another
3. After adding another microsoft account restart the game
4. Now you will only have the first added microsoft account

**Logs/Screenshots/Videos**
Providing logs can be helpful in solving issues. If you crashed, you _must_ provide a crash report and/or a log file. Logs are usually named latest.log, and can be found in the logs folder. If you have one of these, please paste it to [Github Gist](https://gist.github.com/) or [Ubuntu Pastebin](https://paste.ubuntu.com/) and provide the link here. Do *not* attach the log file directly.

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.8.9
 - Mod Version: 7.1.1
 - Loader type: Forge
 - Loader version 11.15.1.1722

**Comment by VidTuGit** [comment]
Fixed in 7.1.2.
