### ISSUE TITLE
Support for the altening

### ISSUE THREAD

**Issue by SubGplayz** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#43]
A lot of users use the altening and would want a way to switch to these temporary alt accounts. I think that it would be a good feature for this mod to do this.

**Comment by The-Fireplace** [comment]
So, what you're asking for is to support a site that offers free accounts? That's sketchy, not going to happen.

**Comment by ShayBox** [comment]
It's been around a long time and many login managers support it

**Comment by ZribeDev** [comment]
Hello, @Offenderify your github is not open anymore.

**Comment by VidTu** [comment]
> Hello, @Offenderify your github is not open anymore.

she won't be on the internet (from this account at least) anymore due to some irl problems
