### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by iBikky** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#44]
I do java -Djava.library.path=C:\Users\bigchungusverified\AppData\Roaming\.minecraft\versions\1.12.2-forge-14.23.5.2854\natives -jar headlessforge.jar C:\Users\bigchungusverified\AppData\Roaming\.minecraft and it still crashes

**Comment by VidTuGit** [comment]
**That's not the In-Game-Account-Switcher bug, if you need support, join the [The_Fireplace's Discord](https://discord.gg/yzVJ4jJ9) or contact me in Discord directly: VidTu#4994 or [twitter](https://twitter.com/imvidtu) or [telegram](https://t.me/imvidtu) or maybe at my nearby store**

You should point to the "-Djava.library.path" property to your "natives" folder. Some launchers (including some versions of official) store it in ".minecraft/versions/VERSIONNAME/natives" folder, some store in ".minecraft/bin/SOME_UUID".

There are two ways of acquiring the exact "natives" directory:
1. Get launch command. On Windows this can be done via command: `wmic process where "name='javaw.exe'" get commandline /format:list` ([picture](https://user-images.githubusercontent.com/60929459/133067962-e7b9c45a-999f-4f78-949a-b73d4d084a13.png)) *(Don't share full command, it contains your auth ID at the end)*
2. Download "natives" from official Mojang maven and unpack where you want (and point "-Djava.library.path" to the unpacked folder): [windows-lwjgl-natives-1.12.2](https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar) [osx-lwjgl-natives-1.12.2](https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar) [linux-lwjgl-natives-1.12.2](https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar)
