### ISSUE TITLE
Exit to multiplayer menu if entered in multiplayer menu.

### ISSUE THREAD

**Issue by UnJust1ce** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#45]
**Is your feature request related to a problem? Please describe.**
If you go into the account switcher menu from the multiplayer menu, when you go out, it takes you back to the main menu.

**Describe the solution you'd like**
I think it would be better if it put you in the multiplayer menu if you clicked the icon in the multiplayer menu.

**Comment by VidTuGit** [comment]
Added in 7.1.3.
