### ISSUE TITLE
Linking Microsoft Accounts.

### ISSUE THREAD

**Issue by skyde-py** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#47]
Whenever I go to click the Microsoft Account Login this shows up
![image](https://user-images.githubusercontent.com/63376310/139592980-72acaf30-b461-4ea4-8c40-0b261a2211fa.png)
and im not sure what the problem is

I am on Version 7.1.2 on Minecraft 1.8.9 forge 4 Gigs of Ram and using Java version 8 Build 311

**Comment by VidTu** [comment]
The Microsoft authentication system uses port `59125` as a "redirector listener" (that page with "You can close this window now"). This port can't be changed (Technically, it can be, but I need to update some details on the Microsoft application page every time this port is changed). Make sure you didn't open some other server on this port (A Minecraft server, Web server, etc.) and you don't have lagged instance of the Minecraft with IAS mod in the background.

**Comment by captstubby** [comment]
not sure where else to put it but I got the same error on 1.18.2 with mod ver 7.1.3 java 1.8.0_281

had installed a no telemetry mod and disabling it fixed my issue. Just wanted to put that out there in case someone else runs into the same error under different conditions

**Comment by VidTu** [comment]
Should be fixed in 8.0.0. (Assuming you've nothing running on port `59125` and no other mods prevent you from running local server on that port)
