### ISSUE TITLE
Accounts not logging in 

### ISSUE THREAD

**Issue by gloiae** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#48]
After using about 10 accounts in a short time im getting mojang banned or so and can't log into new accounts before the last beta update there were no problems there.

-To Reproduce-
switch between 10-20 accounts in a short time

log:
https://gist.github.com/gloiae/944bcbb1bcc624e3f82ee4d8e9feaea8

 - Minecraft: [1.17.1]
 - Mod Version: [7.1.3]
 - Loader type: [Fabric]
 - Loader version [0.11.6]
 - Fabric API: [Fabric API 0.40.1+1.17]

**Comment by VidTu** [comment]
I think I should use a shared clientToken for all Mojang accounts.

**Comment by VidTu** [comment]
Mojang accounts are now deprecated.
