### ISSUE TITLE
Bulk Account Adding

### ISSUE THREAD

**Issue by Metacinnabar** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#49]
**Is your feature request related to a problem? Please describe.**
It is annoying to go through multiple accounts and adding them one by one, and I feel like there could be a better way of adding multiple at a time.

**Describe the solution you'd like**
I suggest a "bulk add" UI, where you can edit your own filter, for example `email:pass` or `pass:email` where it would look for `email` and `pass` and match it from a provided text document or large input box.

**Additional context**
This would be helpful for players who play on anarchy servers to load all their alts at once.

**Comment by VidTu** [comment]
I don't like adding something like this. Accounts in bulk often come from some shady sources like "Minecraft Accounts for $0.1" sites or "TheAltening"-like services. This won't work with Microsoft accounts.

**Comment by The-Fireplace** [comment]
Agreed, large account lists often come from shady sources, which we do not support. If you have legitimately purchased a few accounts, you can add them one by one.

**Comment by VidTu** [comment]
ALSO, Mojang accounts using `email:pass` system [will stop working soon](https://www.minecraft.net/en-us/article/last-call-voluntarily-migrate-java-accounts).

**Comment by Metacinnabar** [comment]
:+1:
