### ISSUE TITLE
How do I compile this in Linux? (sh gradlew build doesn't work)

### ISSUE THREAD

**Issue by NiiightmareXD** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#52]

**Comment by The-Fireplace** [comment]
1. Open terminal in the folder.
2. Use `./gradlew build`
3. If that failed due to not being executable, use `sudo chmod +x gradlew` then try again

**Comment by The-Fireplace** [comment]
Closing this for now, comment if you still have issues.
