### ISSUE TITLE
Login Microsoft 

### ISSUE THREAD

**Issue by IgnGlitch** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#55]
#Login Issues With Microsoft# 
                                                                                      
  When I try to login with microsoft it saved the last account i used to login so now if i change my account i have to relanch the game to get on my main account ![image](https://user-images.githubusercontent.com/102485496/161340057-61f65d4e-e14a-416e-97f8-74006ec901ee.png)

**Comment by VidTu** [comment]
Just add the main account into the mod?..

**Comment by IgnGlitch** [comment]
when i login like that it says wrong login

**Comment by VidTu** [comment]
It can't say "Wrong login" for Microsoft authentication in the Minecraft, because you don't have to enter your Microsoft credentials into mod.
Maybe you're using Mojang login system for Microsoft account.

**Comment by VidTu** [comment]
Should be fixed in 7.2.0.
