### ISSUE TITLE
I get this issue when using the microsofft option on mod: 1.8.9-1.7.3

### ISSUE THREAD

**Issue by Lakkaka** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#56]
I get this error: Unknown error javax.net.ss,SSLHandshakeException: sun.security.validator ValidatorException: PKIN path building failed: sun.security.provider,certpath.SunCertPathBuilderException:
unable to find valid certification path to requested target

**Comment by VidTu** [comment]
#53
