### ISSUE TITLE
This account doesnt own the game

### ISSUE THREAD

**Issue by ampgussudasd** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#57]
**Describe the bug**

**To Reproduce**
4. See error.

**Logs/Screenshots/Videos**
Providing logs can be helpful in solving issues. If you crashed, you _must_ provide a crash report and/or a log file. Logs are usually named latest.log, and can be found in the logs folder. If you have one of these, please paste it to [Github Gist](https://gist.github.com/) or [Ubuntu Pastebin](https://paste.ubuntu.com/) and provide the link here. Do *not* attach the log file directly.

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: [e.g. 1.16.5]
 - Mod Version: [e.g. 7.1]
 - Loader type: [e.g. Fabric]
 - Loader version [e.g. 0.11.3]
 - (Fabric only) Fabric API: [e.g. Fabric API 0.19.0 build 398]

**Comment by ampgussudasd** [comment]
When i try to login using microsoft it says this account doesnt own the game even tho i already own the game

**Comment by VidTu** [comment]
Are you sure you're using the right account?

**Comment by 0x17s** [comment]
when i click microsoft button and click yes on the website it says i dont own the game but im using the right account

**Comment by 0x17s** [comment]
![2022-05-14_00 19 06](https://user-images.githubusercontent.com/105510985/168327938-637f50c9-63ed-4dd7-b770-4476018587cd.png)

**Comment by VidTu** [comment]
Should be fixed in 7.2.0.
