### ISSUE TITLE
Help With Dev

### ISSUE THREAD

**Issue by ThnksCJ** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#60]
im manking my own alt manager for a client but i cant get the microsoft login url correct and it always fails

**Comment by VidTu** [comment]
That's not an issue of the mod.
I've made Microsoft authentication using [wiki.vg](https://wiki.vg/Microsoft_Authentication_Scheme).
You can also look how Microsoft authentication implemented in [MiniLauncher](https://github.com/MiniDigger/MiniLauncher/blob/master/launcher/src/main/java/me/minidigger/minecraftlauncher/launcher/gui/MsaFragmentController.java) or [MultiMC](https://github.com/MultiMC/Launcher/blob/develop/launcher/minecraft/auth/MinecraftAccount.cpp).
Also, you can join The_Fireplace's [Discord server](https://discord.gg/VyhgvvqamS) for help.
