### ISSUE TITLE
Not allowing switching in both directions

### ISSUE THREAD

**Issue by 533kr** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#62]
As title--I'm able to switch _to_ my alt account, but if I launch the game logged in on my alt already, I'm unable to switch to my main. I've tried to add my main account multiple times and whenever I put in the credentials, I'm shown a message telling me the account is already on the list. The list in question, however, only shows my alt no matter which account I'm logged in as.

**Comment by VidTu** [comment]
It should now let you add your account in 7.2.0.
