### ISSUE TITLE
Incompatibility between In Game Account Switcher and Custom Main Menu

### ISSUE THREAD

**Issue by Shady0935** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#63]
Hello, I have a modpack that includes the customization of the start menu using the In Game Account Switcher mod, but due to this mod, the button to switch accounts disappears, is there any way to implement this button in your custom menu?

**Comment by VidTu** [comment]
You need to use custom button with the `104027` ID like this entry:
```json
    "ias": {
        "text": "IAS",
        "posX": -25,
        "posY": 160,
        "width": 50,
        "height": 20,
        "wrappedButton": 104027
    }
```
([Full example configuration](https://paste.gg/p/VidTu/f7cf1c74b91d47a0ad85c68d885d6d01))
You can join [The_Fireplace's Discord](https://discord.gg/vq4DYbHtP2) if you need help with the CMM.
