### ISSUE TITLE
Microsoft login page not showing

### ISSUE THREAD

**Issue by nivowski** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#66]
**Describe the bug**
Whenever I try to add a microsoft account, the page doesn't show

**To Reproduce**
1. Go to Account Switch menu
2. Select Add Account
3. Select Microsoft tab
4. Browser with microsoft page isnt showing

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.8.9
 - Mod Version: 7.1.3.1
 - Loader type: Forge
 - Loader version: recommended (Forge website)
 - OS: Lubuntu 21.04 | Linux

**Comment by VidTu** [comment]
Should be fixed in 8.0.0.
