### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by rory233** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#67]
### Describe the bug

I was using the mod again for about a day, because I got an email that 7.2.0 fixed the problem I reported before. (basically just i wasn't able to login to most accounts, especially microsoft ones. it also would duplicate accounts a bunch until i had like 200 repeat accounts that all didn't let me login) Now the same thing is happening again, I play for a few hours and then my game does this and locks me out of all microsoft accounts, mojang ones seem to be fine though. https://gyazo.com/89311ab840c8d6f4c3e8d8716c2b589e Relogging in does nothing

### To Reproduce

1. launch game
2. play for a few hours
3. can't login to any microsoft accounts with this msg https://gyazo.com/89311ab840c8d6f4c3e8d8716c2b589e

### Minecraft Version

Forge 1.16.5, latest version of the mod as well, also using optifine and a coordinates mod (battys coordinates mod)

### Logs/Screenshots/Videos

https://gyazo.com/89311ab840c8d6f4c3e8d8716c2b589e

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by rory233** [comment]
oh something big i forgot was i logged into my friends account but it had a microsoft authenticator app connected to it. it asked me for the pin but i don't have his phone so i couldn't really login. the error msg says checkgameownership so it might be my fault for logging into a protected account

**Comment by VidTu** [comment]
Delete the account from the mod and add it again. I've tested various Microsoft accounts (with and w/o Microsoft authenticator app) and (unless you're changing your accounts faster than 30 times per minute) it works just fine.

**Comment by VidTu** [comment]
No response.
