### ISSUE TITLE
Doesn't recognize accounts ported from Bedrock[Bug] 

### ISSUE THREAD

**Issue by ChromexUnderscore** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#68]
### Describe the bug

Microsoft Accounts with Bedrock just got Java for free, and the other way around.
I had another Microsoft Account where I bought Bedrock, and I tried to add to the Mod, to quickly switch to it.
It lets me login to my Account through the Browser, but once it's done and I go back to Minecraft, it says that The Account doesn't have Minecraft, and i need to check if I bought the Game.
I'm able to play Minecraft on this account from the Launcher though.

### To Reproduce

1. Launch the Game.
2. Log into an Account that recently received Java as a bundle with Bedrock.
3. The mod tells you that you don't own the Game.

### Minecraft Version

Fabric 1.18.2

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
I don't really have a way to test this (I don't have any accounts ported from Bedrock), but it should be fixed in 8.0.0 because I removed verification that "you've bought Minecraft".
