### ISSUE TITLE
Unable to find a valid certification path to requested target

### ISSUE THREAD

**Issue by Ruochenfu2011** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#69]
#53 Still not fix
See #53 

**To Reproduce**
I don't think you can

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.8.9
 - Mod Version: 7.1.0
 - Loader type: Forge
 - Loader version 11.15.1.2318

**Comment by VidTu** [comment]
Forge 1.8.9 is dead for development in IntelliJ IDEA.
I'll try to update it in my free time, but no promises.

**Comment by VidTu** [comment]
Should be fixed in 8.0.0.
