### ISSUE TITLE
Can this mod be trusted?

### ISSUE THREAD

**Issue by vidod92952** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#70]
title, i dont know java.

**Comment by VidTu** [comment]
Well, any developer of some mod will always say that this mod **can be trusted**.
This mod is open source, so you can check it by yourself or ask someone who knows Java.
You don't have to enter your password (unless you're using Mojang authentication, and if you're using it you should [migrate your account](https://help.minecraft.net/hc/en-us/articles/4403181904525-How-to-Migrate-Your-Mojang-Account-to-a-Microsoft-Account)) and (if you're using Microsoft authentication) you can always revoke your session at https://account.live.com/consent/Manage
