### ISSUE TITLE
[Feature] Switch account icon isn't aligned with other icons.

### ISSUE THREAD

**Issue by UsainSrht** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#71]
### Related problem

Switch icon is 1 pixel smaller than other icons.

### Describe the solution you'd like

![Screenshot_1](https://user-images.githubusercontent.com/59025999/176265754-922b2f1c-d5e1-40fa-aca9-9c4676eb57fc.png)

### Additional context

I didn't realise this until I use replay mod. Replay mod's icon is aligned with minecraft's accessibility icon.

**Comment by VidTu** [comment]
Ok, the funny thing. It's not the button problem. The button is still 20x20 like other buttons, but the texture is 19x20.
It was done to fit the logo (without being misaligned horizontally) into old button. The texture is still misaligned vertically tho.
IDK what to do about this.
![image](https://user-images.githubusercontent.com/60929459/176619965-d96ae644-a609-4caf-aba1-13053cfb7ec2.png)
