### ISSUE TITLE
[Feature] CustomMainMenu 

### ISSUE THREAD

**Issue by FireslasherCodes** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#72]
### Related problem

Just asking, whats the GUI name in java? I'm using a mod called CustonMainMenu to customize the menu of Minecraft. Im adding a button to redirect to the mod page.

### Describe the solution you'd like

Just reply :D

**Comment by VidTu** [comment]
It's not a GUI name but a [wrapped button](https://github.com/lumien231/Custom-Main-Menu/wiki/Wrapped-buttons) `wrappedButton: 104027`.

**Comment by VidTu** [comment]
All legacy buttons should be fixed (have the ID of `104027`) in 8.0.0.
