### ISSUE TITLE
[Feature] Make red text hidable.

### ISSUE THREAD

**Issue by kirmerk1** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#74]
### Related problem

Can't hide red text.

### Describe the solution you'd like

Give us an option to hide this text in mod's config. Thank you.
![Безымянный](https://user-images.githubusercontent.com/83837475/179508811-5285140a-1192-4379-8ca3-dd1335f6ba56.png)

**Comment by mrniddala** [comment]
Hello, I would love to have this too.
Great mod - greetings.

**Comment by VidTu** [comment]
Added in 8.0.0.

**Comment by mrniddala** [comment]
Awesome, thanks 😊
