### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ProtonBlitz** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#75]
### Describe the bug

the game doesn't exactly crash, but it always forces me to restart whenever I select a specific account. idk why it would do that, considering it lets me login just I can't join any servers. Account is not cracked or anything like that, it's a perfectly normal account although it's mojang. Worked just fine a few weeks ago with the same version of everything

### To Reproduce

Launch game
Select account
Try to join server

### Minecraft Version

Fabric 1.18.1

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
Mojang accounts is deprecated and Mojang started forcing everyone to upgrade to Microsoft accounts, so sorry, it's "mandatory migration".

**Comment by ProtonBlitz** [comment]
oh alright, is there any way for me to retrieve the info stored in the mod? I don't have the log in anymore and this was the only place I was logged into it since the migration.

**Comment by VidTu** [comment]
You can get the `accessToken` and `refreshToken` from `.minecraft/config/ias.json`, if you [know what to do with it](https://wiki.vg/Authentication), login and/or password is not stored inside the mod.

**Comment by ProtonBlitz** [comment]
i got the access and refresh token, but im sorta completely lost on how to do it. is there any simple method for using the token to log in to a server? or will it always be pretty complicated

**Comment by VidTu** [comment]
It'll always be complicated, why not migrate your account?
