### ISSUE TITLE
[Bug] Error loading ( ... has failed to load correctly ) 

### ISSUE THREAD

**Issue by diyudule** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#76]
### Describe the bug

Start the game and then crash
Minecraft 1.19
Forge 41.1.0
MOD：one
Java：18.0.1
![QQ截图20220728011040](https://user-images.githubusercontent.com/29426186/181309972-4b382372-8b34-42ee-8013-b6d5401f3045.png)

### To Reproduce

1.Play
2.Error loading

### Minecraft Version

forge 1.19

### Logs/Screenshots/Videos

https://gist.github.com/diyudule/6ace3c6dfa2c5dbbbbaf8c04088320e6

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
Should be fixed in 8.0.0.
