### ISSUE TITLE
[Bug] authMinecraft response: 403

### ISSUE THREAD

**Issue by KingOsuperSuper** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#77]
### Describe the bug

When I login minecraft by Microsoft,The error happened :(

### To Reproduce

1. Launch the game
2. Click `the account button`
3. Click `Add Account`
4. Click `Microsoft`
5. Login
6. The error happened

### Minecraft Version

Fabric 1.18.2

### Logs/Screenshots/Videos

[![vkSVpj.png](https://s1.ax1x.com/2022/07/31/vkSVpj.png)](https://imgtu.com/i/vkSVpj)

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by akemin-dayo** [comment]
Does this still occur with IAS 8.0.0?

**Comment by VidTu** [comment]
No response.
