### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by proladno** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#81]
### Describe the bug

game crashed when i change/login as offline account called KiroAlcyion in a singleplayer modpack so i can use the multiple minecolonies as different account

### To Reproduce

1.Launch Game
2. Switch to offline Account
3. launch singleplayer world
4. crashes

[crash-2022-08-26_13.23.34-client.txt](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/files/9430115/crash-2022-08-26_13.23.34-client.txt)
[crash-2022-08-26_13.26.58-client.txt](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/files/9430117/crash-2022-08-26_13.26.58-client.txt)

### Minecraft Version

Forge 1.18.2

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by proladno** [comment]
i used the alpha version of the mod and the issue seems fixed however instead it rename my singleplayer character instead of making new ones :(

**Comment by The-Fireplace** [comment]
> i used the alpha version of the mod and the issue seems fixed however instead it rename my singleplayer character instead of making new ones :(

That's how Singleplayar works, you could log into a second real account and have the same issue. If you want server-like handling, run a server on your local machine and connect to it, thus creating a singleplayer experience that treats different names differently.
