### ISSUE TITLE
[Bug] Invalid Session

### ISSUE THREAD

**Issue by OoLunar** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#82]
### Describe the bug

When attempting to log in with an offline account on an offline server, I get the error "invalid session." I am unsure if this is intentional or if I am using the mod incorrectly, however, I find this behavior undesirable when I'm hosting a server for my household.

### To Reproduce

1. Login with a premium account
2. Switch to an offline account
3. Attempt to login into an offline server

### Minecraft Version

(Fabric 1.19.2) InGameAccountSwitcher-Fabric-1.19-8.0.0.jar

### Logs/Screenshots/Videos

N/A

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
If you're getting "Invalid session.", this is not an offline server. (you can test if this is an offline server by absence of players' heads in the player list)
Offline server:
![image](https://user-images.githubusercontent.com/60929459/187093765-5069b966-3a02-4e4d-a6a4-8b52467ea4c2.png)
Online server:
![image](https://user-images.githubusercontent.com/60929459/187093776-95978202-4070-4eac-9b62-03332aa995a6.png)

**Comment by OoLunar** [comment]
You are indeed correct, this was a user error. I was using EasyAuth on the server and was having trouble connecting because the username I had was already taken by a premium MC account. I.E, `Aphmau` wouldn't be allowed, but `fdjifojweioff` would be accepted. My fault, apologies again.
