### ISSUE TITLE
[Feature] Can there be a way to update my access token?

### ISSUE THREAD

**Issue by Antiflux** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#83]
### Related problem

Hello, I use MultiMC as my launcher. I use MultiMC to manage my accounts and credentials. I run my different accounts in separate game instances.

I don't actually switch accounts ingame, because the instances for the separate accounts have different configurations. I don't want to set up this mod to manage multiple accounts ingame, I use this mod solely for the feature whereby it shows on the main screen "You are logged in as USERNAME".

The problem, of course, is that credentials expire, and I don't want to have to exit and restart the game when I have to refresh my access token.

### Describe the solution you'd like

Is there a possibility that this mod could added a feature that lets me just paste in the text of a new access token, and keep playing with updated credentials that way?

**Comment by VidTu** [comment]
Firstly, where are you gonna grab the new access token?
Secondly, if you're using different instances, why not add only your current account (on every instance) into the mod and refresh access token via the mod? Config for the mod is stored in instance folder, not somewhere globally in your system.

**Comment by Antiflux** [comment]
Firstly, I have an instance set up for debugging launch issues, that instead of running the game it displays all the launch parameters including the access token.
Secondly, because the launcher insists on managing the accounts anyway, I can't stop it from managing them, and I'd prefer not to have competing setups fighting over whose access token is current.

**Comment by VidTu** [comment]
This is a feature I don't consider adding into the mod.
