### ISSUE TITLE
Unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by Belloooo** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#85]
### Describe the bug

This is the error I get whenever I try to switch to an other account in my account list or even add one. I`ve tried restarting my game, installing the 8.0 version of the mod and installing the newest version of java but nothing seems to help.

https://paste.pics/ab047728162187bc822ac31eae095d6d

### To Reproduce

1. Launch The Game
2. Go to the account switcher
3. Try to log in to a different account or adding a new account to your account list
4. 

### Minecraft Version

Fabric 1.18.2

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by bAdOoWindy** [comment]
also happen in Fabric 1.19.2

**Comment by D3st0ny** [comment]
same

**Comment by ProfessionalBoatDrifter** [comment]
Same here. Also Fabric 1.19.2

**Comment by honzapatCZ** [comment]
Same here 1.18.2

**Comment by vladbogun1** [comment]
does someone found solution for that bug?

**Comment by honzapatCZ** [comment]
Nope, I even tried editing keystores to add the xbox.live server, but its not working.
Makes life of developing online mods pretty hard tbh, this could have simpliefied it.
I suppose maybe xbox changed the endpoint?
Anyways it's now up to these 2 gods. 
@VidTu @The-Fireplace

**Comment by VidTu** [comment]
Okay, I'm not at home to update certificates and the mod, but you can try opening mod file via any archiver (just file manager on Linux/Mac, 7Zip/WinRar on Windows) and deleting iasjavafix.jks file inside as a temporary workaround.

**Comment by honzapatCZ** [comment]
Wait, for the whole time it was because the mod has its own keystore. Fuckin damn it. I was modifying the java one all the time xd.

**Comment by VidTu** [comment]
The mod has its own keystore for Java 8u51 which is distributed by Mojang for older versions and I forgot to disable it for 1.17+

**Comment by VidTu** [comment]
P.S. Fix already in progress.

**Comment by bAdOoWindy** [comment]
Oh Good!

**Comment by VidTu** [comment]
Should be fixed in 8.0.1.
