### ISSUE TITLE
Authentication fails using 7.2 version for 1.19.0 fabric

### ISSUE THREAD

**Issue by Totoro51212** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#87]
### Describe the bug

Opening the game works fine, but when trying to switch accounts an error is given

### To Reproduce

1. Launch the game with 1.19.0 fabric, latest fabric api for 1.19.0, and In game account switcher for 1.19.0
2.0 try to switch accounts, it will not do anything.

### Minecraft Version

Fabric 1.19.0

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
7.2.x version is old, please use 8.0.1 version for 1.19.1/2.
If you want to use 8.0.1 version for 1.19.0, use [this fork](https://github.com/akemin-dayo/In-Game-Account-Switcher/releases).
