### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by giorgiaxoba** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#88]
### Describe the bug

![image](https://user-images.githubusercontent.com/67603262/193449154-856d3495-5d77-43a0-aa00-7cc9f7d2e25b.png)
this is what it says when i try to login from microsoft

### To Reproduce

i click on add account after that microsoft after that i enter the stuff and i click on yes when it asks me if i want to let this access my acc. After that it says "java.net.ssl.SSLHandshakeException:sun.security.validator.ValidatorException:PKIX  unable to find valid certification path to requested target" 
![image](https://user-images.githubusercontent.com/67603262/193449190-b240d183-9b50-404b-9e34-e391c3afd414.png)

### Minecraft Version

1.8.9 

### Checklist

- [x] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
I've tested everything with the latest mod and Forge version on vanilla and MultiMC launchers. Are you sure that you're using the latest mod version?

**Comment by VidTu** [comment]
No response. (Stale)
