### ISSUE TITLE
[Bug] Mod has no compatibility with RLCraft

### ISSUE THREAD

**Issue by EmersonJorgyCreate** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#89]
### Describe the bug

The account button does not appear when I launch RLCraft.
The mod is in the mods folder.

### To Reproduce

Install RLCraft, and add the mod (Acount switcher) to the pack.
Once the pack is loaded, there will be no button displayed to switch accounts.

### Minecraft Version

Forge 1.12.2

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
RLCraft uses CustomMainMenu, so you need to configure that for button to display correctly. Configuration guide for CustomMainMenu is available on their wiki, you'll need to use a wrapped button with ID: `104027`.

**Comment by EmersonJorgyCreate** [comment]
How would I do that though?
