### ISSUE TITLE
[Bug]  {short bug description here}

### ISSUE THREAD

**Issue by Galagz** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#91]
### Describe the bug

i cannot add an account to the account switcher because an error always pops up 
Error java.lang.IllegalArgumentException: authXSTS response: 401
idk what to do if anyone could help me that would be awesome

### To Reproduce

i launch the game go to the account switcher square click add microsoft chose an account tells me to close the window and the error pops up
![3967EA61-2DF8-4570-8C4B-2C9C9566E515](https://user-images.githubusercontent.com/115164779/194396427-7b91c6bc-f222-43e3-8727-f32e560485d2.png)

### Minecraft Version

Fabric 1.18.2

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
Unable to reproduce on Forge and Fabric. Have you tried removing and re-adding your account?

**Comment by VidTu** [comment]
No response.

**Comment by zkinorama** [comment]
It could be because your microsoft account is not 18 years old yet and not linked to a family
