### ISSUE TITLE
getProfile response: 404, 429

### ISSUE THREAD

**Issue by Ramezsushi** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#92]
### Describe the bug

Whenever I try to switch accounts, I get met with 

                          An error has occured

 java.lang.IllegalArgumentException: getProfile response: 404
 
 sometimes the error code is also 429, the mod was working a few days ago for me but seems to have stopped working.

### To Reproduce

1. Launch Fabric 1.19.2
2. Click on the Account Switcher button
3. Switch Accounts, if it fails at "getProfile" (the second time it appears since it also appears at the start), I get the error code 404, if it fails at "authMinecraft", I get 429.

### Minecraft Version

Fabric 1.19.2

### Checklist

- [x] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [x] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
Does it still occur with the latest mod version?

**Comment by akemin-dayo** [comment]
While I can't say for sure that this is the exact case for Ramezsushi, I've definitely seen this strange state occur on a friend's Microsoft account.

In her case, what had happened was that her Microsoft account somehow got temporarily disassociated from the underlying Mojang profile — this was an issue purely on Microsoft's backend, and had nothing to do with IAS.

With her specific account, even trying to launch Minecraft through the launcher would erroneously prompt the "Enter a username for Minecraft: Java Edition" alert, where typing in her existing Mojang username would result in "Username has already been taken."

What ended up fixing it was a simple visit to https://minecraft.net/profile/ and clicking on "Profile Name" (※ no other change was required).

Afterwards, both IAS and the Minecraft Launcher resumed proper operation.

Again, I'm not sure if this is the case for OP, but it was definitely a case I've come across.

**Comment by Ramezsushi** [comment]
> With her specific account, even trying to launch Minecraft through the launcher would erroneously prompt the "Enter a username for Minecraft: Java Edition" alert, where typing in her existing Mojang username would result in "Username has already been taken."

Interesting, I've had that occur once on an alt account but never on my main one, when I was still using the mod that never occurred though

**Comment by Ramezsushi** [comment]
> Does it still occur with the latest mod version?

I no longer use the mod unfortunately so I am unable to assist further with this issue
