### ISSUE TITLE
[Feature] Ability to open login GUI through keybind or multiplayer menu

### ISSUE THREAD

**Issue by DarkGamer209788** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#93]
### Related problem

Are there any alternative ways to open the login menu?

### Describe the solution you'd like

Can you make the login menu available on the multiplayer tab or accessible through a keybind?

**Comment by VidTu** [comment]
Account list is already available, you can enable it in the config.

**Comment by DarkGamer209788** [comment]
Thank you for that!
