### ISSUE TITLE
[Bug] refreshToken response: 400

### ISSUE THREAD

**Issue by UltraBlackLinux** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#97]
### Describe the bug

Trying to log in errors with `refreshToken response: 400`

### To Reproduce

Press log in

### Minecraft Version

1.19.2

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
Unable to reproduce on Forge and Fabric. Have you tried removing and re-adding your account?

**Comment by UltraBlackLinux** [comment]
oh wow that actually ended up working. Thanks!
