### ISSUE TITLE
[Bug] java.net.BindException

### ISSUE THREAD

**Issue by BoxDevelopment** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#98]
### Describe the bug

when i attempt to log on to a minecraft account i get a error saying
java.net.BindException: Address already in use: bind

### To Reproduce

1: load up
2: attempt to log into a account
3: get error 

### Minecraft Version

Fabric 1.19.2 and Forge 1.8.9

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by HiHi3690** [comment]
Issue is also present on my machine, so it is not an issue of one person's PC

**Comment by VidTu** [comment]
Something in your system is using port `59125` for something else.

###### TODO (for myself): Microsoft allows multiple callback URLs (and ports), use this and maybe use MultiMC-like code auth.
