### ISSUE TITLE
[Bug] 1.19.3 is not supported

### ISSUE THREAD

**Issue by WzczChenX** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#99]
### Describe the bug

Open 1.19.3 game crash with the latest version

### To Reproduce

1. start game
2. game crashes

### Minecraft Version

Fabric 1.19.3

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)
- [X] I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version

**Comment by VidTu** [comment]
Fixed in 8.0.1.1.
